Repository zaryar/Image-AugmentationTP, pull requests merged in 2023-05, with the labels that each got.

#11 Ein paar Änderungen in front vorgenommen
  local proof of concept/front/Images/1682336678203.jpg
  local proof of concept/front/MartinTestWebsite/PHP NEEDS TO BE INSTALLED
  local proof of concept/front/MartinTestWebsite/demo.php
  local proof of concept/front/MartinTestWebsite/uploader.htm
  local proof of concept/front/index.js
  local proof of concept/front/main.html
  local proof of concept/front/public/css/style.css
  local proof of concept/front/public/images/input/test.png
  local proof of concept/front/public/images/output/test.png
  local proof of concept/front/public/javaScripts/script.js
Labels: frontend

#15 Zusätzliche Filter #07
  local proof of concept/back/filters.py
Labels: backend

#16 added simple for-loop
  local proof of concept/back/main.ipynb
Labels: backend

#12 added a configuration text file
  local proof of concept/front/index.js
  local proof of concept/front/main.html
  local proof of concept/front/public/configData.txt
Labels: frontend, communication

#18 snapshot button now updates the configData file
  local proof of concept/front/index.js
  local proof of concept/front/main.html
Labels: frontend, communication

#30 changed file names and added 25pfs to input
  local proof of concept/front/index.js
  local proof of concept/front/main.html
  local proof of concept/front/public/javaScripts/webcam.js
Labels: frontend

#33 read config file as txt and added python loop to detect action.
  local_proof_of_concept/back/main.py
Labels: backend

#36 deleted the filter_rotate filter
  local proof of concept/back/filters.py
Labels: backend

#53 Added config and live stream for every second
  local_version/back/main.py
  local_version/front/index.js
Labels: backend, frontend, communication
