Repository zaryar/Image-AugmentationTP, pull requests merged in 2023-07, with the labels that each got.

#101 compressed images to jpg with reduced quality
  local_version/back/main.py
  local_version/front/index.js
  local_version/front/public/javaScripts/webcam.js
Labels: bug, backend, frontend, communication

#106 Thraenbe/style transfer auf server
  local_version/back/fast_ns/experiments/utils.py
  local_version/back/main.py
Labels: backend

#107 Ns fix#104
  local_version/back/fast_ns/experiments/filters_for_images.py
  local_version/back/fast_ns/experiments/utils.py
  local_version/back/main.py
  local_version/front/main.html
Labels: backend

#114 documented main.py
  local_version/back/main.py
Labels: documentation

#118 Thraenbe/scale images
  local_version/back/fast_ns/experiments/utils.py
  local_version/back/main.py
  local_version/front/public/javaScripts/webcam.js
Labels: backend, frontend, communication
