Repository zaryar/Image-AugmentationTP, pull requests merged in 2023-06, with the labels that each got.

#60 added dropdown menu and ability to choose 2 filters
  local_version/front/index.js
  local_version/front/main.html
  local_version/front/public/css/style.css
  local_version/front/public/javaScripts/script.js
  local_version/front/public/javaScripts/webcam.js
Labels: bug, frontend, communication

#61 added feature to stop stream
  local_version/back/main.py
Labels: backend

#83 Mediapipe filters on cpu
  local_version/back/faceRec_MP/faceBlendCommon.py
  local_version/back/faceRec_MP/filters/LandmarkMask.png
  local_version/back/faceRec_MP/filters/cat-ears.png
  local_version/back/faceRec_MP/filters/cat-ears_annotations.csv
  local_version/back/faceRec_MP/filters/cat-nose.png
  local_version/back/faceRec_MP/filters/cat-nose_annotations.csv
  local_version/back/faceRec_MP/filters/clown.png
  local_version/back/faceRec_MP/filters/dog-ears.png
  local_version/back/faceRec_MP/filters/dog-ears_annotations.csv
  local_version/back/faceRec_MP/filters/dog-nose.png
  local_version/back/faceRec_MP/filters/dog-nose_annotations.csv
  local_version/back/faceRec_MP/filters/flower-crown.png
  local_version/back/faceRec_MP/filters/flower-crown_annotations.csv
  local_version/back/faceRec_MP/filters/gold-crown.png
  local_version/back/faceRec_MP/filters/gold-crown_annotations.csv
  local_version/back/faceRec_MP/filters/landmarks80.csv
  local_version/back/faceRec_MP/mediapipeFilter.py
  local_version/data/input/face_video.mp4
  local_version/data/input/video_lowQual.mp4
Labels: backend

#92 changed config again
  local_version/back/main.py
Labels: communication

#93 created enviroment for face_reg stream
  local_version/back/faceRec_MP/mediapipeFilter.py
  local_version/back/main.py
Labels: communication

#94 refactored and added stylize option for stream25
  local_version/back/main.py
Labels: documentation, backend
